### ISSUE TITLE
Lobby menu - cursor appears where it shouldn't

### ISSUE THREAD

**Issue by Deadrit** [Muph0/hunger-games-simulator#6]
When you switch back to the left menu while the `Chat:` option is selected, the cursor appears in playerlist and since the playerlist isn't redrawn from that moment the cursor stays there until you switch to right.

![screenshot](http://image.prntscr.com/image/8f50ba9d9cff42c98456ae66f47ab14c.png)

**Comment by Muph0** [comment]
fixed in 7236b9a3132d8d9540f39cbb0196afc83c978f4f
